import { PendingApproval, Dispute, Alert, SellerStats, OrderStats, RevenueStats } from './types';

export const demoDashboardData: {
  sellerStats: SellerStats;
  orderStats: OrderStats;
  revenueStats: RevenueStats;
} = {
  sellerStats: {
    total: 2847,
    active: 2156,
    inactive: 691,
    newToday: 12,
    newThisWeek: 68,
    newThisMonth: 245,
    pendingApproval: 34,
  },
  orderStats: {
    total: 156789,
    pending: 1245,
    processing: 2890,
    shipped: 3456,
    delivered: 145678,
    cancelled: 3520,
    todayOrders: 892,
    todayGrowth: 12.5,
  },
  revenueStats: {
    gmv: 458900000,
    gmvGrowth: 18.5,
    platformRevenue: 45890000,
    revenueGrowth: 22.3,
    commissionRate: 10,
    todayRevenue: 1250000,
    weeklyRevenue: 8900000,
    monthlyRevenue: 38500000,
  },
};

export const demoPendingApprovals: PendingApproval[] = [
  {
    id: 'approval-1',
    type: 'seller',
    title: 'New Seller Registration',
    description: 'Tech Solutions BD - Electronics & Gadgets store',
    submittedBy: 'Rakib Hasan',
    submittedAt: '2026-01-24T08:30:00Z',
    priority: 'high',
  },
  {
    id: 'approval-2',
    type: 'seller',
    title: 'New Seller Registration',
    description: 'Fashion Forward - Women\'s clothing boutique',
    submittedBy: 'Nadia Akter',
    submittedAt: '2026-01-24T07:15:00Z',
    priority: 'medium',
  },
  {
    id: 'approval-3',
    type: 'product',
    title: 'Product Listing Review',
    description: 'iPhone 15 Pro Max - Requires authenticity verification',
    submittedBy: 'Mobile Hub',
    submittedAt: '2026-01-24T09:00:00Z',
    priority: 'high',
  },
  {
    id: 'approval-4',
    type: 'product',
    title: 'Product Listing Review',
    description: 'Organic Honey Bundle - Health claims verification needed',
    submittedBy: 'Nature\'s Best',
    submittedAt: '2026-01-24T06:45:00Z',
    priority: 'medium',
  },
  {
    id: 'approval-5',
    type: 'withdrawal',
    title: 'Withdrawal Request',
    description: 'Large withdrawal - Additional verification required',
    submittedBy: 'Fashion House',
    submittedAt: '2026-01-24T05:30:00Z',
    priority: 'high',
    amount: 850000,
  },
  {
    id: 'approval-6',
    type: 'withdrawal',
    title: 'Withdrawal Request',
    description: 'Regular weekly withdrawal',
    submittedBy: 'Beauty Box',
    submittedAt: '2026-01-24T04:00:00Z',
    priority: 'low',
    amount: 125000,
  },
  {
    id: 'approval-7',
    type: 'withdrawal',
    title: 'Withdrawal Request',
    description: 'First-time withdrawal - Identity verification pending',
    submittedBy: 'New Electronics',
    submittedAt: '2026-01-23T22:00:00Z',
    priority: 'high',
    amount: 45000,
  },
  {
    id: 'approval-8',
    type: 'seller',
    title: 'Seller Tier Upgrade',
    description: 'Request to upgrade from Silver to Gold tier',
    submittedBy: 'Sports Corner',
    submittedAt: '2026-01-23T18:00:00Z',
    priority: 'low',
  },
];

export const demoDisputes: Dispute[] = [
  {
    id: 'dispute-1',
    orderId: 'ORD-2026-045678',
    type: 'fraud',
    status: 'pending',
    buyer: 'Kamal Hossain',
    seller: 'Quick Electronics',
    amount: 45000,
    createdAt: '2026-01-24T10:00:00Z',
    description: 'Buyer claims product is counterfeit. Seller denies allegations.',
  },
  {
    id: 'dispute-2',
    orderId: 'ORD-2026-045123',
    type: 'quality',
    status: 'in_progress',
    buyer: 'Fatima Begum',
    seller: 'Fashion Deals',
    amount: 8500,
    createdAt: '2026-01-23T14:00:00Z',
    description: 'Product quality does not match description. Fabric is different.',
  },
  {
    id: 'dispute-3',
    orderId: 'ORD-2026-044890',
    type: 'delivery',
    status: 'pending',
    buyer: 'Rahim Uddin',
    seller: 'Home Goods Plus',
    amount: 12000,
    createdAt: '2026-01-23T09:00:00Z',
    description: 'Order marked as delivered but buyer claims not received.',
  },
  {
    id: 'dispute-4',
    orderId: 'ORD-2026-044567',
    type: 'refund',
    status: 'escalated',
    buyer: 'Nasreen Akter',
    seller: 'Beauty Corner',
    amount: 5500,
    createdAt: '2026-01-22T16:00:00Z',
    description: 'Refund approved but not processed after 7 days.',
  },
  {
    id: 'dispute-5',
    orderId: 'ORD-2026-044234',
    type: 'fraud',
    status: 'pending',
    buyer: 'Imran Khan',
    seller: 'Tech Bargains',
    amount: 95000,
    createdAt: '2026-01-22T11:00:00Z',
    description: 'Suspected bait-and-switch. Advertised specs don\'t match delivered product.',
  },
];

export const demoAlerts: Alert[] = [
  {
    id: 'alert-1',
    severity: 'critical',
    title: 'Potential Fraud Detected',
    message: 'Unusual order pattern detected from seller "Quick Electronics" - 15 high-value orders in last hour with same payment method.',
    source: 'Fraud Detection System',
    timestamp: '2026-01-24T10:15:00Z',
    isRead: false,
    actionRequired: true,
  },
  {
    id: 'alert-2',
    severity: 'critical',
    title: 'Payment Gateway Issue',
    message: 'bKash payment gateway showing 15% failure rate in last 30 minutes. Technical team notified.',
    source: 'Payment Monitor',
    timestamp: '2026-01-24T09:45:00Z',
    isRead: false,
    actionRequired: true,
  },
  {
    id: 'alert-3',
    severity: 'warning',
    title: 'Abnormal Sales Spike',
    message: 'Seller "Fashion House" showing 500% sales increase in last 2 hours. Review recommended.',
    source: 'Sales Analytics',
    timestamp: '2026-01-24T09:30:00Z',
    isRead: false,
    actionRequired: true,
  },
  {
    id: 'alert-4',
    severity: 'warning',
    title: 'High Refund Rate',
    message: 'Seller "Budget Mart" has 25% refund rate this week, exceeding 10% threshold.',
    source: 'Quality Monitor',
    timestamp: '2026-01-24T08:00:00Z',
    isRead: true,
    actionRequired: true,
  },
  {
    id: 'alert-5',
    severity: 'warning',
    title: 'Inventory Sync Failed',
    message: '12 sellers have inventory sync issues. Stock levels may be inaccurate.',
    source: 'Inventory System',
    timestamp: '2026-01-24T07:30:00Z',
    isRead: true,
    actionRequired: false,
  },
  {
    id: 'alert-6',
    severity: 'info',
    title: 'Daily Backup Complete',
    message: 'System backup completed successfully. All data secured.',
    source: 'System',
    timestamp: '2026-01-24T06:00:00Z',
    isRead: true,
    actionRequired: false,
  },
  {
    id: 'alert-7',
    severity: 'info',
    title: 'New Milestone Reached',
    message: 'Platform has crossed 150,000 total orders! 🎉',
    source: 'Analytics',
    timestamp: '2026-01-24T05:30:00Z',
    isRead: true,
    actionRequired: false,
  },
];
