import { Notice, Recipient, NoticeStats } from './types';

export const demoSellers: Recipient[] = [
  { id: 'seller-1', name: 'Ahmed Rahman', email: 'ahmed@techstore.com', type: 'seller', avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop', shopName: 'Tech Store BD' },
  { id: 'seller-2', name: 'Fatima Begum', email: 'fatima@fashionhub.com', type: 'seller', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop', shopName: 'Fashion Hub' },
  { id: 'seller-3', name: 'Mohammad Hasan', email: 'hasan@electronics.com', type: 'seller', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop', shopName: 'Electronics World' },
  { id: 'seller-4', name: 'Rashida Khatun', email: 'rashida@homegoods.com', type: 'seller', avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop', shopName: 'Home Goods BD' },
  { id: 'seller-5', name: 'Karim Uddin', email: 'karim@grocerymart.com', type: 'seller', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop', shopName: 'Grocery Mart BD' },
  { id: 'seller-6', name: 'Salma Akter', email: 'salma@beautyshop.com', type: 'seller', avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop', shopName: 'Beauty Shop' },
];

export const demoShops: Recipient[] = [
  { id: 'shop-1', name: 'Tech Store BD', email: 'contact@techstore.com', type: 'shop' },
  { id: 'shop-2', name: 'Fashion Hub', email: 'contact@fashionhub.com', type: 'shop' },
  { id: 'shop-3', name: 'Electronics World', email: 'contact@electronics.com', type: 'shop' },
  { id: 'shop-4', name: 'Home Goods BD', email: 'contact@homegoods.com', type: 'shop' },
  { id: 'shop-5', name: 'Grocery Mart BD', email: 'contact@grocerymart.com', type: 'shop' },
  { id: 'shop-6', name: 'Beauty Shop', email: 'contact@beautyshop.com', type: 'shop' },
  { id: 'shop-7', name: 'Sports Zone', email: 'contact@sportszone.com', type: 'shop' },
  { id: 'shop-8', name: 'Book Corner', email: 'contact@bookcorner.com', type: 'shop' },
];

export const demoNotices: Notice[] = [
  {
    id: 'notice-1',
    title: 'Platform Maintenance Scheduled',
    content: 'We will be performing scheduled maintenance on January 25, 2026, from 2:00 AM to 6:00 AM BST. During this time, the platform may be temporarily unavailable. Please plan your activities accordingly.\n\nWhat to expect:\n- Order processing will be paused\n- Dashboard access may be intermittent\n- All scheduled tasks will resume after maintenance',
    type: 'maintenance',
    priority: 'high',
    status: 'sent',
    recipientType: 'all_sellers',
    recipients: [],
    recipientCount: 156,
    readCount: 134,
    createdAt: '2026-01-20T10:00:00Z',
    sentAt: '2026-01-20T10:30:00Z',
    expiresAt: '2026-01-26T00:00:00Z',
    createdBy: 'Admin',
  },
  {
    id: 'notice-2',
    title: 'New Commission Structure Update',
    content: 'We are updating our commission structure effective February 1, 2026. The new rates will be:\n\n- Electronics: 8% (previously 10%)\n- Fashion: 12% (previously 15%)\n- Groceries: 5% (previously 7%)\n\nThis change reflects our commitment to supporting seller growth. Please review the detailed breakdown in your seller dashboard.',
    type: 'policy',
    priority: 'urgent',
    status: 'sent',
    recipientType: 'all_sellers',
    recipients: [],
    recipientCount: 156,
    readCount: 98,
    createdAt: '2026-01-18T09:00:00Z',
    sentAt: '2026-01-18T09:15:00Z',
    createdBy: 'Admin',
  },
  {
    id: 'notice-3',
    title: 'Flash Sale Participation Invitation',
    content: 'You are invited to participate in our upcoming Flash Sale event on January 28-30, 2026. Register your products by January 26 to be featured.\n\nBenefits:\n- Featured placement on homepage\n- Promotional email inclusion\n- Increased visibility',
    type: 'promotion',
    priority: 'medium',
    status: 'sent',
    recipientType: 'individual_seller',
    recipients: [demoSellers[0], demoSellers[1], demoSellers[2]],
    recipientCount: 3,
    readCount: 2,
    createdAt: '2026-01-19T14:00:00Z',
    sentAt: '2026-01-19T14:30:00Z',
    createdBy: 'Marketing Team',
  },
  {
    id: 'notice-4',
    title: 'Product Listing Guidelines Update',
    content: 'We have updated our product listing guidelines to ensure better customer experience. Please review and update your listings accordingly:\n\n1. All products must have at least 3 high-quality images\n2. Descriptions must be accurate and detailed\n3. Pricing must include all applicable taxes\n\nNon-compliant listings may be temporarily hidden.',
    type: 'update',
    priority: 'high',
    status: 'scheduled',
    recipientType: 'all_shops',
    recipients: [],
    recipientCount: 89,
    readCount: 0,
    createdAt: '2026-01-22T11:00:00Z',
    scheduledAt: '2026-01-24T09:00:00Z',
    createdBy: 'Admin',
  },
  {
    id: 'notice-5',
    title: 'Congratulations on Your Performance!',
    content: 'Your shop has been performing exceptionally well this month! You are now eligible for our "Top Seller" badge. This badge will be displayed on your shop profile and products.\n\nKeep up the great work!',
    type: 'announcement',
    priority: 'low',
    status: 'sent',
    recipientType: 'individual_shop',
    recipients: [demoShops[0]],
    recipientCount: 1,
    readCount: 1,
    createdAt: '2026-01-21T16:00:00Z',
    sentAt: '2026-01-21T16:00:00Z',
    createdBy: 'Performance Team',
  },
  {
    id: 'notice-6',
    title: 'Warning: Policy Violation Detected',
    content: 'We have detected potential policy violations in your recent product listings. Please review and correct the following issues within 48 hours:\n\n- Misleading product descriptions\n- Incorrect pricing information\n\nFailure to address these issues may result in listing suspension.',
    type: 'warning',
    priority: 'urgent',
    status: 'sent',
    recipientType: 'individual_seller',
    recipients: [demoSellers[3]],
    recipientCount: 1,
    readCount: 1,
    createdAt: '2026-01-22T08:00:00Z',
    sentAt: '2026-01-22T08:05:00Z',
    createdBy: 'Compliance Team',
  },
  {
    id: 'notice-7',
    title: 'Valentine\'s Day Campaign',
    content: 'Get ready for Valentine\'s Day! We are launching a special campaign from February 7-14. Register your romantic gift items to be featured in our special collection.',
    type: 'promotion',
    priority: 'medium',
    status: 'draft',
    recipientType: 'all_sellers',
    recipients: [],
    recipientCount: 0,
    readCount: 0,
    createdAt: '2026-01-23T10:00:00Z',
    createdBy: 'Marketing Team',
  },
];

export const calculateNoticeStats = (notices: Notice[]): NoticeStats => {
  const sentNotices = notices.filter(n => n.status === 'sent');
  const totalRecipients = sentNotices.reduce((sum, n) => sum + n.recipientCount, 0);
  const totalRead = sentNotices.reduce((sum, n) => sum + n.readCount, 0);
  
  return {
    totalNotices: notices.length,
    sentNotices: sentNotices.length,
    scheduledNotices: notices.filter(n => n.status === 'scheduled').length,
    draftNotices: notices.filter(n => n.status === 'draft').length,
    totalRecipients,
    avgReadRate: totalRecipients > 0 ? (totalRead / totalRecipients) * 100 : 0,
  };
};
