import {
  CategorySales,
  SellerRanking,
  ChurnData,
  ChurnReason,
  HighRiskSeller,
  FunnelData,
  AnalyticsSummary,
} from './types';

export const demoCategories: CategorySales[] = [
  {
    id: 'cat-1',
    name: 'Electronics',
    icon: '📱',
    totalSales: 4850000,
    totalOrders: 1245,
    growth: 18.5,
    avgOrderValue: 3896,
    topProduct: 'Samsung Galaxy S24',
    color: 'bg-blue-500',
  },
  {
    id: 'cat-2',
    name: 'Fashion',
    icon: '👗',
    totalSales: 3200000,
    totalOrders: 2890,
    growth: 12.3,
    avgOrderValue: 1107,
    topProduct: 'Designer Saree Collection',
    color: 'bg-pink-500',
  },
  {
    id: 'cat-3',
    name: 'Beauty & Health',
    icon: '💄',
    totalSales: 1850000,
    totalOrders: 1560,
    growth: 25.8,
    avgOrderValue: 1186,
    topProduct: 'Organic Skincare Set',
    color: 'bg-purple-500',
  },
  {
    id: 'cat-4',
    name: 'Home & Living',
    icon: '🏠',
    totalSales: 2100000,
    totalOrders: 890,
    growth: 8.2,
    avgOrderValue: 2360,
    topProduct: 'Smart Home Bundle',
    color: 'bg-emerald-500',
  },
  {
    id: 'cat-5',
    name: 'Sports & Fitness',
    icon: '🏃',
    totalSales: 980000,
    totalOrders: 620,
    growth: 32.1,
    avgOrderValue: 1581,
    topProduct: 'Premium Yoga Mat Set',
    color: 'bg-orange-500',
  },
  {
    id: 'cat-6',
    name: 'Food & Grocery',
    icon: '🍎',
    totalSales: 1450000,
    totalOrders: 3200,
    growth: 15.6,
    avgOrderValue: 453,
    topProduct: 'Organic Honey Bundle',
    color: 'bg-green-500',
  },
  {
    id: 'cat-7',
    name: 'Books & Stationery',
    icon: '📚',
    totalSales: 450000,
    totalOrders: 890,
    growth: -2.4,
    avgOrderValue: 506,
    topProduct: 'IELTS Preparation Set',
    color: 'bg-indigo-500',
  },
  {
    id: 'cat-8',
    name: 'Jewelry',
    icon: '💎',
    totalSales: 2800000,
    totalOrders: 420,
    growth: 22.7,
    avgOrderValue: 6667,
    topProduct: 'Gold Plated Necklace',
    color: 'bg-yellow-500',
  },
];

export const demoSellerRankings: SellerRanking[] = [
  {
    id: 'seller-1',
    rank: 1,
    previousRank: 1,
    name: 'Mohammad Rahman',
    shopName: 'Tech World BD',
    avatar: 'https://randomuser.me/api/portraits/men/1.jpg',
    totalSales: 2450000,
    totalOrders: 856,
    rating: 4.9,
    growth: 28.5,
    conversionRate: 8.2,
    tier: 'platinum',
  },
  {
    id: 'seller-2',
    rank: 2,
    previousRank: 4,
    name: 'Fatima Akter',
    shopName: 'Fashion House',
    avatar: 'https://randomuser.me/api/portraits/women/2.jpg',
    totalSales: 1980000,
    totalOrders: 1245,
    rating: 4.8,
    growth: 45.2,
    conversionRate: 7.8,
    tier: 'platinum',
  },
  {
    id: 'seller-3',
    rank: 3,
    previousRank: 2,
    name: 'Karim Hossain',
    shopName: 'Beauty Box',
    avatar: 'https://randomuser.me/api/portraits/men/3.jpg',
    totalSales: 1650000,
    totalOrders: 980,
    rating: 4.7,
    growth: 12.3,
    conversionRate: 6.5,
    tier: 'gold',
  },
  {
    id: 'seller-4',
    rank: 4,
    previousRank: 3,
    name: 'Nusrat Jahan',
    shopName: 'Jewel Palace',
    avatar: 'https://randomuser.me/api/portraits/women/4.jpg',
    totalSales: 1420000,
    totalOrders: 320,
    rating: 4.9,
    growth: -5.8,
    conversionRate: 9.1,
    tier: 'gold',
  },
  {
    id: 'seller-5',
    rank: 5,
    previousRank: 7,
    name: 'Imran Sheikh',
    shopName: 'Sports Corner',
    avatar: 'https://randomuser.me/api/portraits/men/5.jpg',
    totalSales: 980000,
    totalOrders: 540,
    rating: 4.6,
    growth: 58.9,
    conversionRate: 5.8,
    tier: 'silver',
  },
  {
    id: 'seller-6',
    rank: 6,
    previousRank: 5,
    name: 'Sabina Yasmin',
    shopName: 'Heritage Crafts',
    avatar: 'https://randomuser.me/api/portraits/women/6.jpg',
    totalSales: 890000,
    totalOrders: 456,
    rating: 4.8,
    growth: 8.2,
    conversionRate: 7.2,
    tier: 'silver',
  },
  {
    id: 'seller-7',
    rank: 7,
    previousRank: 6,
    name: 'Tanvir Ahmed',
    shopName: 'Gamer Zone',
    avatar: 'https://randomuser.me/api/portraits/men/7.jpg',
    totalSales: 750000,
    totalOrders: 380,
    rating: 4.5,
    growth: 15.6,
    conversionRate: 6.8,
    tier: 'silver',
  },
  {
    id: 'seller-8',
    rank: 8,
    previousRank: 10,
    name: 'Anika Rahman',
    shopName: 'Nutrition Plus',
    avatar: 'https://randomuser.me/api/portraits/women/8.jpg',
    totalSales: 620000,
    totalOrders: 890,
    rating: 4.7,
    growth: 42.3,
    conversionRate: 5.2,
    tier: 'bronze',
  },
  {
    id: 'seller-9',
    rank: 9,
    previousRank: 8,
    name: 'Rafiq Islam',
    shopName: 'Book Haven',
    avatar: 'https://randomuser.me/api/portraits/men/9.jpg',
    totalSales: 480000,
    totalOrders: 720,
    rating: 4.6,
    growth: -8.5,
    conversionRate: 4.8,
    tier: 'bronze',
  },
  {
    id: 'seller-10',
    rank: 10,
    previousRank: 9,
    name: 'Mina Begum',
    shopName: 'Home Essentials',
    avatar: 'https://randomuser.me/api/portraits/women/10.jpg',
    totalSales: 420000,
    totalOrders: 280,
    rating: 4.4,
    growth: 5.2,
    conversionRate: 4.5,
    tier: 'bronze',
  },
];

export const demoChurnData: ChurnData[] = [
  { period: 'Jan', activeUsers: 45000, churnedUsers: 1800, churnRate: 4.0, newUsers: 3200, netGrowth: 1400 },
  { period: 'Feb', activeUsers: 46400, churnedUsers: 1624, churnRate: 3.5, newUsers: 2800, netGrowth: 1176 },
  { period: 'Mar', activeUsers: 47576, churnedUsers: 1903, churnRate: 4.0, newUsers: 3500, netGrowth: 1597 },
  { period: 'Apr', activeUsers: 49173, churnedUsers: 1475, churnRate: 3.0, newUsers: 2900, netGrowth: 1425 },
  { period: 'May', activeUsers: 50598, churnedUsers: 2024, churnRate: 4.0, newUsers: 3100, netGrowth: 1076 },
  { period: 'Jun', activeUsers: 51674, churnedUsers: 1550, churnRate: 3.0, newUsers: 2700, netGrowth: 1150 },
  { period: 'Jul', activeUsers: 52824, churnedUsers: 2113, churnRate: 4.0, newUsers: 3800, netGrowth: 1687 },
  { period: 'Aug', activeUsers: 54511, churnedUsers: 1635, churnRate: 3.0, newUsers: 2600, netGrowth: 965 },
  { period: 'Sep', activeUsers: 55476, churnedUsers: 2219, churnRate: 4.0, newUsers: 3200, netGrowth: 981 },
  { period: 'Oct', activeUsers: 56457, churnedUsers: 1694, churnRate: 3.0, newUsers: 2900, netGrowth: 1206 },
  { period: 'Nov', activeUsers: 57663, churnedUsers: 2306, churnRate: 4.0, newUsers: 3500, netGrowth: 1194 },
  { period: 'Dec', activeUsers: 58857, churnedUsers: 1766, churnRate: 3.0, newUsers: 4200, netGrowth: 2434 },
];

export const demoChurnReasons: ChurnReason[] = [
  { reason: 'Poor delivery experience', count: 3250, percentage: 28.5 },
  { reason: 'Found better prices elsewhere', count: 2180, percentage: 19.1 },
  { reason: 'Product quality issues', count: 1890, percentage: 16.6 },
  { reason: 'Limited product variety', count: 1450, percentage: 12.7 },
  { reason: 'Payment issues', count: 980, percentage: 8.6 },
  { reason: 'App/Website usability', count: 850, percentage: 7.5 },
  { reason: 'Customer service', count: 800, percentage: 7.0 },
];

export const demoHighRiskSellers: HighRiskSeller[] = [
  {
    id: 'risk-1',
    name: 'Abdul Karim',
    shopName: 'Quick Electronics',
    avatar: 'https://randomuser.me/api/portraits/men/11.jpg',
    riskScore: 92,
    riskLevel: 'critical',
    riskFactors: ['High return rate (25%)', 'Multiple complaints', 'Declining sales (-45%)', 'Late shipments'],
    lastOrderDate: '2026-01-18T10:00:00Z',
    salesTrend: -45,
    complaintRate: 18.5,
    returnRate: 25.0,
    recommendation: 'Immediate review required. Consider suspension if not improved within 7 days.',
  },
  {
    id: 'risk-2',
    name: 'Shamim Haque',
    shopName: 'Budget Mart',
    avatar: 'https://randomuser.me/api/portraits/men/12.jpg',
    riskScore: 85,
    riskLevel: 'critical',
    riskFactors: ['Fake product reports', 'Rating dropped to 2.8', 'Refund requests spike'],
    lastOrderDate: '2026-01-20T10:00:00Z',
    salesTrend: -32,
    complaintRate: 22.3,
    returnRate: 18.5,
    recommendation: 'Product authenticity verification needed. Temporary hold on new listings.',
  },
  {
    id: 'risk-3',
    name: 'Nasreen Akter',
    shopName: 'Fashion Deals',
    avatar: 'https://randomuser.me/api/portraits/women/11.jpg',
    riskScore: 78,
    riskLevel: 'high',
    riskFactors: ['Size/color mismatch complaints', 'Slow response time', 'Declining ratings'],
    lastOrderDate: '2026-01-22T10:00:00Z',
    salesTrend: -28,
    complaintRate: 15.2,
    returnRate: 20.0,
    recommendation: 'Quality control review. Mandatory product description update required.',
  },
  {
    id: 'risk-4',
    name: 'Jamal Uddin',
    shopName: 'Home Goods Plus',
    avatar: 'https://randomuser.me/api/portraits/men/13.jpg',
    riskScore: 72,
    riskLevel: 'high',
    riskFactors: ['Inventory discrepancies', 'Order cancellation rate 15%', 'Stock issues'],
    lastOrderDate: '2026-01-21T10:00:00Z',
    salesTrend: -18,
    complaintRate: 12.8,
    returnRate: 14.0,
    recommendation: 'Inventory management training. Sync system audit required.',
  },
  {
    id: 'risk-5',
    name: 'Rubina Khatun',
    shopName: 'Cosmetics Corner',
    avatar: 'https://randomuser.me/api/portraits/women/12.jpg',
    riskScore: 65,
    riskLevel: 'medium',
    riskFactors: ['Product expiry concerns', 'Packaging complaints', 'Response delay'],
    lastOrderDate: '2026-01-23T10:00:00Z',
    salesTrend: -12,
    complaintRate: 9.5,
    returnRate: 11.0,
    recommendation: 'Product shelf life monitoring. Customer service improvement plan.',
  },
  {
    id: 'risk-6',
    name: 'Habib Rahman',
    shopName: 'Tech Bargains',
    avatar: 'https://randomuser.me/api/portraits/men/14.jpg',
    riskScore: 58,
    riskLevel: 'medium',
    riskFactors: ['Warranty claim issues', 'Documentation problems', 'Slight sales decline'],
    lastOrderDate: '2026-01-22T10:00:00Z',
    salesTrend: -8,
    complaintRate: 7.2,
    returnRate: 9.5,
    recommendation: 'Warranty process review. Documentation compliance check.',
  },
];

export const demoFunnelData: FunnelData = {
  totalViews: 1250000,
  addedToCart: 187500,
  checkoutInitiated: 75000,
  ordersCompleted: 45000,
  conversionRate: 3.6,
  cartAbandonmentRate: 60.0,
  checkoutAbandonmentRate: 40.0,
};

export const demoAnalyticsSummary: AnalyticsSummary = {
  totalRevenue: 17680000,
  revenueGrowth: 18.5,
  totalOrders: 12890,
  ordersGrowth: 15.2,
  activeUsers: 58857,
  usersGrowth: 12.8,
  avgOrderValue: 1372,
  aovGrowth: 2.8,
  conversionRate: 3.6,
  conversionGrowth: 0.4,
  churnRate: 3.5,
  churnChange: -0.5,
};
