import { Seller } from './types';

export const demoSellers: Seller[] = [
  {
    id: '1',
    name: 'Ahmed Rahman',
    email: 'ahmed@techstore.com',
    phone: '+880 1712-345678',
    avatar: 'https://ui-avatars.com/api/?name=Ahmed+Rahman&background=6366f1&color=fff',
    status: 'verified',
    tier: 'gold',
    businessInfo: {
      businessName: 'Tech Store BD',
      businessType: 'Electronics Retail',
      registrationNumber: 'REG-2023-001234',
      taxId: 'TIN-123456789',
      address: '123 Gulshan Avenue',
      city: 'Dhaka',
      state: 'Dhaka Division',
      zipCode: '1212',
      country: 'Bangladesh',
      phone: '+880 2-9876543',
      email: 'info@techstore.com',
      website: 'www.techstore.com.bd',
      establishedYear: 2018,
    },
    documents: [
      {
        id: 'd1',
        type: 'trade_license',
        name: 'Trade License 2024',
        url: '/documents/trade-license-1.pdf',
        status: 'approved',
        uploadedAt: '2024-01-15',
        expiryDate: '2025-12-31',
      },
      {
        id: 'd2',
        type: 'nid',
        name: 'National ID Card',
        url: '/documents/nid-1.pdf',
        status: 'approved',
        uploadedAt: '2024-01-15',
      },
      {
        id: 'd3',
        type: 'tax_certificate',
        name: 'Tax Certificate 2024',
        url: '/documents/tax-1.pdf',
        status: 'approved',
        uploadedAt: '2024-02-01',
        expiryDate: '2025-06-30',
      },
    ],
    performance: {
      totalOrders: 1250,
      completedOrders: 1180,
      cancelledOrders: 25,
      rating: 4.8,
      reviewCount: 890,
      cancellationRate: 2.0,
      responseTime: 1.5,
      onTimeDeliveryRate: 96.5,
    },
    penalties: [],
    createdAt: '2023-03-15',
    lastActive: '2026-01-23',
    totalRevenue: 2500000,
    balance: 45000,
  },
  {
    id: '2',
    name: 'Fatima Begum',
    email: 'fatima@fashionhub.com',
    phone: '+880 1812-987654',
    avatar: 'https://ui-avatars.com/api/?name=Fatima+Begum&background=ec4899&color=fff',
    status: 'verified',
    tier: 'silver',
    businessInfo: {
      businessName: 'Fashion Hub',
      businessType: 'Clothing & Apparel',
      registrationNumber: 'REG-2022-005678',
      taxId: 'TIN-987654321',
      address: '456 Dhanmondi Road',
      city: 'Dhaka',
      state: 'Dhaka Division',
      zipCode: '1205',
      country: 'Bangladesh',
      phone: '+880 2-8765432',
      email: 'contact@fashionhub.com',
      website: 'www.fashionhub.com.bd',
      establishedYear: 2020,
    },
    documents: [
      {
        id: 'd4',
        type: 'trade_license',
        name: 'Trade License 2024',
        url: '/documents/trade-license-2.pdf',
        status: 'approved',
        uploadedAt: '2024-01-20',
        expiryDate: '2025-12-31',
      },
      {
        id: 'd5',
        type: 'nid',
        name: 'National ID Card',
        url: '/documents/nid-2.pdf',
        status: 'approved',
        uploadedAt: '2024-01-20',
      },
    ],
    performance: {
      totalOrders: 650,
      completedOrders: 610,
      cancelledOrders: 18,
      rating: 4.5,
      reviewCount: 420,
      cancellationRate: 2.8,
      responseTime: 2.0,
      onTimeDeliveryRate: 94.0,
    },
    penalties: [
      {
        id: 'p1',
        type: 'warning',
        reason: 'Late delivery reported multiple times',
        startDate: '2025-11-15',
        isActive: false,
        createdBy: 'Admin User',
      },
    ],
    createdAt: '2022-08-10',
    lastActive: '2026-01-22',
    totalRevenue: 850000,
    balance: 12000,
  },
  {
    id: '3',
    name: 'Mohammad Hasan',
    email: 'hasan@electronics.com',
    phone: '+880 1912-456789',
    avatar: 'https://ui-avatars.com/api/?name=Mohammad+Hasan&background=22c55e&color=fff',
    status: 'unverified',
    tier: 'bronze',
    businessInfo: {
      businessName: 'Hasan Electronics',
      businessType: 'Electronics Wholesale',
      registrationNumber: 'REG-2024-009876',
      taxId: 'TIN-456789123',
      address: '789 Motijheel Commercial Area',
      city: 'Dhaka',
      state: 'Dhaka Division',
      zipCode: '1000',
      country: 'Bangladesh',
      phone: '+880 2-7654321',
      email: 'info@hasanelectronics.com',
      establishedYear: 2024,
    },
    documents: [
      {
        id: 'd6',
        type: 'trade_license',
        name: 'Trade License 2024',
        url: '/documents/trade-license-3.pdf',
        status: 'pending',
        uploadedAt: '2025-01-10',
        expiryDate: '2025-12-31',
      },
      {
        id: 'd7',
        type: 'nid',
        name: 'National ID Card',
        url: '/documents/nid-3.pdf',
        status: 'pending',
        uploadedAt: '2025-01-10',
      },
    ],
    performance: {
      totalOrders: 45,
      completedOrders: 40,
      cancelledOrders: 3,
      rating: 4.2,
      reviewCount: 28,
      cancellationRate: 6.7,
      responseTime: 4.0,
      onTimeDeliveryRate: 88.0,
    },
    penalties: [],
    createdAt: '2025-01-05',
    lastActive: '2026-01-21',
    totalRevenue: 125000,
    balance: 8500,
  },
  {
    id: '4',
    name: 'Sarah Khan',
    email: 'sarah@beautyworld.com',
    phone: '+880 1612-321654',
    avatar: 'https://ui-avatars.com/api/?name=Sarah+Khan&background=f59e0b&color=fff',
    status: 'suspended',
    tier: 'silver',
    businessInfo: {
      businessName: 'Beauty World',
      businessType: 'Cosmetics & Beauty',
      registrationNumber: 'REG-2021-003456',
      taxId: 'TIN-321654987',
      address: '321 Banani Road',
      city: 'Dhaka',
      state: 'Dhaka Division',
      zipCode: '1213',
      country: 'Bangladesh',
      phone: '+880 2-6543210',
      email: 'hello@beautyworld.com',
      website: 'www.beautyworld.com.bd',
      establishedYear: 2019,
    },
    documents: [
      {
        id: 'd8',
        type: 'trade_license',
        name: 'Trade License 2024',
        url: '/documents/trade-license-4.pdf',
        status: 'approved',
        uploadedAt: '2024-01-25',
        expiryDate: '2025-12-31',
      },
      {
        id: 'd9',
        type: 'nid',
        name: 'National ID Card',
        url: '/documents/nid-4.pdf',
        status: 'approved',
        uploadedAt: '2024-01-25',
      },
    ],
    performance: {
      totalOrders: 520,
      completedOrders: 450,
      cancelledOrders: 45,
      rating: 3.8,
      reviewCount: 310,
      cancellationRate: 8.7,
      responseTime: 6.0,
      onTimeDeliveryRate: 82.0,
    },
    penalties: [
      {
        id: 'p2',
        type: 'temporary_ban',
        reason: 'Multiple customer complaints about product quality',
        startDate: '2026-01-15',
        endDate: '2026-02-15',
        isActive: true,
        createdBy: 'Admin User',
      },
      {
        id: 'p3',
        type: 'fine',
        reason: 'Selling counterfeit products',
        amount: 5000,
        startDate: '2026-01-10',
        isActive: true,
        createdBy: 'Admin User',
      },
    ],
    createdAt: '2021-06-20',
    lastActive: '2026-01-15',
    totalRevenue: 720000,
    balance: -5000,
  },
  {
    id: '5',
    name: 'Karim Uddin',
    email: 'karim@grocerymart.com',
    phone: '+880 1512-654321',
    avatar: 'https://ui-avatars.com/api/?name=Karim+Uddin&background=8b5cf6&color=fff',
    status: 'verified',
    tier: 'platinum',
    businessInfo: {
      businessName: 'Grocery Mart BD',
      businessType: 'Grocery & Food',
      registrationNumber: 'REG-2019-001122',
      taxId: 'TIN-654321789',
      address: '555 Uttara Sector 7',
      city: 'Dhaka',
      state: 'Dhaka Division',
      zipCode: '1230',
      country: 'Bangladesh',
      phone: '+880 2-5432109',
      email: 'support@grocerymart.com',
      website: 'www.grocerymart.com.bd',
      establishedYear: 2017,
    },
    documents: [
      {
        id: 'd10',
        type: 'trade_license',
        name: 'Trade License 2024',
        url: '/documents/trade-license-5.pdf',
        status: 'approved',
        uploadedAt: '2024-01-05',
        expiryDate: '2025-12-31',
      },
      {
        id: 'd11',
        type: 'nid',
        name: 'National ID Card',
        url: '/documents/nid-5.pdf',
        status: 'approved',
        uploadedAt: '2024-01-05',
      },
      {
        id: 'd12',
        type: 'tax_certificate',
        name: 'Tax Certificate 2024',
        url: '/documents/tax-5.pdf',
        status: 'approved',
        uploadedAt: '2024-02-15',
        expiryDate: '2025-06-30',
      },
      {
        id: 'd13',
        type: 'bank_statement',
        name: 'Bank Statement Dec 2024',
        url: '/documents/bank-5.pdf',
        status: 'approved',
        uploadedAt: '2025-01-02',
      },
    ],
    performance: {
      totalOrders: 3200,
      completedOrders: 3150,
      cancelledOrders: 20,
      rating: 4.9,
      reviewCount: 2100,
      cancellationRate: 0.6,
      responseTime: 0.5,
      onTimeDeliveryRate: 99.0,
    },
    penalties: [],
    createdAt: '2019-02-10',
    lastActive: '2026-01-23',
    totalRevenue: 8500000,
    balance: 250000,
  },
  {
    id: '6',
    name: 'Rina Akter',
    email: 'rina@homegoods.com',
    phone: '+880 1412-789456',
    avatar: 'https://ui-avatars.com/api/?name=Rina+Akter&background=ef4444&color=fff',
    status: 'unverified',
    tier: 'bronze',
    businessInfo: {
      businessName: 'Home Goods Store',
      businessType: 'Home & Living',
      registrationNumber: 'REG-2025-000111',
      taxId: 'TIN-789456123',
      address: '888 Mirpur Road',
      city: 'Dhaka',
      state: 'Dhaka Division',
      zipCode: '1216',
      country: 'Bangladesh',
      phone: '+880 2-4321098',
      email: 'contact@homegoods.com',
      establishedYear: 2025,
    },
    documents: [
      {
        id: 'd14',
        type: 'trade_license',
        name: 'Trade License 2025',
        url: '/documents/trade-license-6.pdf',
        status: 'pending',
        uploadedAt: '2025-01-18',
        expiryDate: '2026-12-31',
      },
      {
        id: 'd15',
        type: 'nid',
        name: 'National ID Card',
        url: '/documents/nid-6.pdf',
        status: 'rejected',
        uploadedAt: '2025-01-18',
      },
    ],
    performance: {
      totalOrders: 12,
      completedOrders: 10,
      cancelledOrders: 1,
      rating: 4.0,
      reviewCount: 8,
      cancellationRate: 8.3,
      responseTime: 5.0,
      onTimeDeliveryRate: 85.0,
    },
    penalties: [],
    createdAt: '2025-01-15',
    lastActive: '2026-01-20',
    totalRevenue: 35000,
    balance: 2500,
  },
  {
    id: '7',
    name: 'Imran Ali',
    email: 'imran@sportszone.com',
    phone: '+880 1312-147258',
    avatar: 'https://ui-avatars.com/api/?name=Imran+Ali&background=06b6d4&color=fff',
    status: 'verified',
    tier: 'gold',
    businessInfo: {
      businessName: 'Sports Zone',
      businessType: 'Sports & Fitness',
      registrationNumber: 'REG-2020-007890',
      taxId: 'TIN-147258369',
      address: '222 Mohakhali Commercial Area',
      city: 'Dhaka',
      state: 'Dhaka Division',
      zipCode: '1212',
      country: 'Bangladesh',
      phone: '+880 2-3210987',
      email: 'info@sportszone.com',
      website: 'www.sportszone.com.bd',
      establishedYear: 2018,
    },
    documents: [
      {
        id: 'd16',
        type: 'trade_license',
        name: 'Trade License 2024',
        url: '/documents/trade-license-7.pdf',
        status: 'approved',
        uploadedAt: '2024-01-12',
        expiryDate: '2025-12-31',
      },
      {
        id: 'd17',
        type: 'nid',
        name: 'National ID Card',
        url: '/documents/nid-7.pdf',
        status: 'approved',
        uploadedAt: '2024-01-12',
      },
      {
        id: 'd18',
        type: 'tax_certificate',
        name: 'Tax Certificate 2024',
        url: '/documents/tax-7.pdf',
        status: 'approved',
        uploadedAt: '2024-03-01',
        expiryDate: '2025-06-30',
      },
    ],
    performance: {
      totalOrders: 980,
      completedOrders: 945,
      cancelledOrders: 15,
      rating: 4.7,
      reviewCount: 680,
      cancellationRate: 1.5,
      responseTime: 1.0,
      onTimeDeliveryRate: 97.0,
    },
    penalties: [],
    createdAt: '2020-04-22',
    lastActive: '2026-01-23',
    totalRevenue: 1800000,
    balance: 75000,
  },
  {
    id: '8',
    name: 'Nadia Islam',
    email: 'nadia@bookworld.com',
    phone: '+880 1212-369258',
    avatar: 'https://ui-avatars.com/api/?name=Nadia+Islam&background=84cc16&color=fff',
    status: 'rejected',
    tier: 'bronze',
    businessInfo: {
      businessName: 'Book World',
      businessType: 'Books & Stationery',
      registrationNumber: 'REG-2024-012345',
      taxId: 'TIN-369258147',
      address: '999 Nilkhet Book Market',
      city: 'Dhaka',
      state: 'Dhaka Division',
      zipCode: '1205',
      country: 'Bangladesh',
      phone: '+880 2-2109876',
      email: 'hello@bookworld.com',
      establishedYear: 2024,
    },
    documents: [
      {
        id: 'd19',
        type: 'trade_license',
        name: 'Trade License 2024',
        url: '/documents/trade-license-8.pdf',
        status: 'rejected',
        uploadedAt: '2024-12-01',
        expiryDate: '2025-12-31',
      },
      {
        id: 'd20',
        type: 'nid',
        name: 'National ID Card',
        url: '/documents/nid-8.pdf',
        status: 'rejected',
        uploadedAt: '2024-12-01',
      },
    ],
    performance: {
      totalOrders: 0,
      completedOrders: 0,
      cancelledOrders: 0,
      rating: 0,
      reviewCount: 0,
      cancellationRate: 0,
      responseTime: 0,
      onTimeDeliveryRate: 0,
    },
    penalties: [],
    createdAt: '2024-12-01',
    lastActive: '2024-12-15',
    totalRevenue: 0,
    balance: 0,
  },
];
